### ISSUE TITLE
Doesn't discover existing tags if refs have been packed

### ISSUE THREAD

**Issue by necrophonic** [pkg/rock#3] opened 2017-08-21 19:08 UTC
If a repository has had it's tags packed with `git pack-refs` then `rock tags` returns nothing (and attempting to create a tag assumes current tag is `0.0.0`)

Appears to be an issue with `gogits/git`library (Known issue - Have opened a pull request to attempt to fix the issue)

Issue: https://github.com/gogits/git/issues/27
PR: https://github.com/gogits/git/pull/31

**Comment by bketelsen** [comment] 2017-08-23 16:14
nice.  Ping here when the issue is merged and i'll update dependency.

**Comment by necrophonic** [comment] 2017-10-12 19:18
Original pull request to https://github.com/gogits/git has no been reviewed and appears the package is no longer actively maintained?
Have addressed this issue (and #4?) in PR #8 by proposing switching to use [code.gitea.io/git](https://github.com/go-gitea/git) which is still being updated and correctly handles packed refs.

**Comment by necrophonic** [comment] 2017-10-13 10:07
Update: After posting the above and pr #8, my original pr https://github.com/gogits/git/pull/31 has been merged.

Should mean this issue can be closed by either updating the `gogits/git` dependency or using PR #8 to switch to using [code.gitea.io/git](https://github.com/go-gitea/git).

**Closed as completed** 2017-11-07 13:12 UTC
